# https://github.com/marketplace/actions/deploy-react-app-to-github-pages

name: Deploy to Netlify
on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.0.2
    - run: 'pnpm install' 
    - run: 'pnpm build'
    - uses: South-Paw/action-netlify-deploy@v1.2.0
      with:
        github-token: ${{ secrets.VITE_TOKEN_GITHUB }}
        netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
        build-dir: './dist'

